version: '3.9'

services:

  backend:
    image: node:latest
    container_name: backend
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm run start:dev"
    restart: always
    working_dir: /backend
    volumes:
      - ./backend:/backend
    ports:
      - 3001:3001
    env_file: .env
    platform: linux/x86_64
    depends_on:
      - database
    networks:
      - ngcash_net

  database:
    image: postgres:latest
    container_name: database
    platform: linux/x86_64
    ports:
      - 3002:5432
    env_file: .env
    restart: 'always'
    networks:
      - ngcash_net

networks:
  ngcash_net:
    driver: bridge